### ISSUE TITLE
Installation error with conda enviroment python=3.10.9: Getting requirements to build wheel did not run successfully.

### ISSUE THREAD

**Issue by Gemmavdv** [angelolab/pyFlowSOM#13]
**Describe the bug**
Hi developers team,

I tried to install pyFlowSOM today using a fresh conda environment, and encountered the following error: `Getting requirements to build wheel did not run successfully.` from `ValueError: 'src/pyFlowSOM/cyFlowSOM.pyx' doesn't match any files`. I installed all requirements separately before. Any help would be greatly appreciated, thank you very much in advance.

Best,
Gemma

**Expected behavior**
Successful installation.

**To Reproduce**
```
(base) user@PC:~$ conda create -n flowsom5 python=3.10
(base) user@PC:~$ conda activate flowsom5
(flowsom5) user@PC:~$ pip install pyFlowSOM
Collecting pyFlowSOM
  Using cached pyFlowSOM-0.1.13.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/home/user/anaconda3/envs/flowsom5/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/user/anaconda3/envs/flowsom5/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/user/anaconda3/envs/flowsom5/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-o343zbhk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-o343zbhk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-o343zbhk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
        File "/tmp/pip-build-env-o343zbhk/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 970, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/tmp/pip-build-env-o343zbhk/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/tmp/pip-build-env-o343zbhk/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'src/pyFlowSOM/cyFlowSOM.pyx' doesn't match any files
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(flowsom5) user@PC:~$ conda list
# packages in environment at /home/user/anaconda3/envs/flowsom5:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.01.10           h06a4308_0  
certifi                   2022.12.7       py310h06a4308_0  
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
ncurses                   6.4                  h6a678d5_0  
openssl                   1.1.1s               h7f8727e_0  
pip                       22.3.1          py310h06a4308_0  
python                    3.10.9               h7a1cb2a_0  
readline                  8.2                  h5eee18b_0  
setuptools                65.6.3          py310h06a4308_0  
sqlite                    3.40.1               h5082296_0  
tk                        8.6.12               h1ccaba5_0  
tzdata                    2022g                h04d1e81_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.10               h5eee18b_1  
zlib                      1.2.13               h5eee18b_0  
(flowsom5) user@PC:~$ conda install cython
(flowsom5) user@PC:~$ conda install numpy
(flowsom5) user@PC:~$ conda install scipy
(flowsom5) user@PC:~$ conda list
# packages in environment at /home/user/anaconda3/envs/flowsom5:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
appdirs                   1.4.4              pyhd3eb1b0_0  
blas                      1.0                         mkl  
brotlipy                  0.7.0           py310h7f8727e_1002  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.01.10           h06a4308_0  
certifi                   2022.12.7       py310h06a4308_0  
cffi                      1.15.1          py310h5eee18b_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
cryptography              38.0.4          py310h9ce1e76_0  
cython                    0.29.32         py310h6a678d5_0  
fftw                      3.3.9                h27cfd23_1  
idna                      3.4             py310h06a4308_0  
intel-openmp              2021.4.0          h06a4308_3561  
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            11.2.0               h00389a5_1  
libgfortran5              11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0           py310h7f8727e_0  
mkl_fft                   1.3.1           py310hd6ae3a3_0  
mkl_random                1.2.2           py310h00e6091_0  
ncurses                   6.4                  h6a678d5_0  
numpy                     1.23.5          py310hd5efca6_0  
numpy-base                1.23.5          py310h8e6c178_0  
openssl                   1.1.1s               h7f8727e_0  
packaging                 22.0            py310h06a4308_0  
pip                       22.3.1          py310h06a4308_0  
pooch                     1.4.0              pyhd3eb1b0_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pysocks                   1.7.1           py310h06a4308_0  
python                    3.10.9               h7a1cb2a_0  
readline                  8.2                  h5eee18b_0  
requests                  2.28.1          py310h06a4308_0  
scipy                     1.10.0          py310hd5efca6_0  
setuptools                65.6.3          py310h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.40.1               h5082296_0  
tk                        8.6.12               h1ccaba5_0  
tzdata                    2022g                h04d1e81_0  
urllib3                   1.26.14         py310h06a4308_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.10               h5eee18b_1  
zlib                      1.2.13               h5eee18b_0  
(flowsom5) user@PC:~$ conda clean -t
Will remove 1156 (2.54 GB) tarball(s).
Proceed ([y]/n)? y

(flowsom5) user@PC:~$ pip install pyFlowSOM
Collecting pyFlowSOM
  Using cached pyFlowSOM-0.1.13.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/home/user/anaconda3/envs/flowsom5/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/user/anaconda3/envs/flowsom5/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/user/anaconda3/envs/flowsom5/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-ig62inv2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-ig62inv2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ig62inv2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
        File "/tmp/pip-build-env-ig62inv2/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 970, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/tmp/pip-build-env-ig62inv2/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/tmp/pip-build-env-ig62inv2/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'src/pyFlowSOM/cyFlowSOM.pyx' doesn't match any files
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by srivarra** [comment]
@Gemmavdv Hello! Currently the only version of Python that we built pyFlowSOM for is 3.8, so in order to use it you would need a python 3.8 conda environment.

**Comment by Gemmavdv** [comment]
Thank you! That did the trick :)
