### ISSUE TITLE
AttributeError: module 'scipy' has no attribute 'spatial'

### ISSUE THREAD

**Issue by SachinLearns** [angelolab/pyFlowSOM#20]
**Describe the bug**
I am using Python 3.8.13 and installed pyFlowSOM as explained here: https://pypi.org/project/pyFlowSOM/.
The module is giving me a basic error: _AttributeError: module 'scipy' has no attribute 'spatial_'
I anticipated a normal return of the output. Since it is written in C, I cannot locate/debug the code. Even if someone can guide me where to explore, it would be a help.

**To Reproduce**
I ran the following code:

`node_output  = som(data, seed = 30)`

Note that the data was a 2D numpy array.

The following error was encountered:

> Traceback (most recent call last):
>   File "main.py", line 27, in <module>
>     node_output  = som(data, seed = 30)
>   File "src/pyFlowSOM/cyFlowSOM.pyx", line 100, in pyFlowSOM.cyFlowSOM.som
>   File "src/pyFlowSOM/cyFlowSOM.pyx", line 46, in pyFlowSOM.cyFlowSOM.neighborhood_distance
> AttributeError: module 'scipy' has no attribute 'spatial'

**Comment by cliu72** [comment]
Please check the version of `scipy` you are using in your environment. As the error indicates, `scipy.spatial` (https://docs.scipy.org/doc/scipy/reference/spatial.html) does not seem to be available in your version of scipy. I just created a new conda environment in python 3.8.13 and was able to install and run pyFlowSOM without any error.
